[package]
name = "cmilbert_aoc_day4a"
version = "0.1.0"
edition = "2021"
authors = ["Chris Milbert <cmilbert@>"]

[lib]
name = "cmilbert_aoc_day4a"
path = "src/bingo.rs"

[[bin]]
name = "cmilbert_aoc_day4a"
path = "src/main.rs"

[dependencies]
