[package]
name = "cmilbert_aoc_day7b"
version = "0.1.0"
edition = "2021"
authors = ["Chris Milbert <cmilbert@>"]

[lib]
name = "cmilbert_aoc_day7b"
path = "src/crab.rs"

[[bin]]
name = "cmilbert_aoc_day7b"
path = "src/main.rs"

[dependencies]
