[package]
name = "cmilbert_aoc_day10a"
version = "0.1.0"
edition = "2021"
authors = ["Chris Milbert <cmilbert@>"]

[lib]
name = "cmilbert_aoc_day10a"
path = "src/navigation_subsystem.rs"

[[bin]]
name = "cmilbert_aoc_day10a"
path = "src/main.rs"

[dependencies]
